<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringCompare</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKCVN0cmluZwlzdHJpbmcxID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJzdHJpbmcxIiApOwoJU3RyaW5nCXN0cmluZzIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgInN0cmluZzIiICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsK
CmludCByZXN1bHQgPSBzdHJpbmcxLmNvbXBhcmVUbyhzdHJpbmcyKTsKCi8vIHBpcGVsaW5lCklE
YXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInJlc3VsdCIsIHJlc3VsdCsiIiApOwpwaXBlbGlu
ZUN1cnNvcl8xLmRlc3Ryb3koKTsK</value>
</Values>
