<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doThreadInvoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gZ2V0IHBpcGVsaW5lIGlucHV0IGRhdGEKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBw
aXBlbGluZS5nZXRDdXJzb3IoKTsKCVN0cmluZwl0YXJnZXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgInRhcmdldCIgKTsKCi8vY29uc3RydWN0IGEgbmV3IHNlcnZpY2Ug
dGhyZWFkClNlcnZpY2VUaHJlYWQgc3QgPSBudWxsOwoKLy90cnkgdG8gY2xvbmUgdGhlIHBpcGVs
aW5lIGFuZCBleGVjdXRlIHRocmVhZGVkIGludm9rZQovL3RoaXMgcHJvdGVjdHMgdGhlIHRocmVh
ZCBpbnZva2UgZnJvbSBzdWJzZXF1ZW50IGNoYW5nZXMgdG8gdGhlIHBpcGVsaW5lCklEYXRhIGNs
b25lZFBpcGUgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7CnRyeQp7CgljbG9uZWRQaXBlID0gSURh
dGFVdGlsLmRlZXBDbG9uZShwaXBlbGluZSk7CQoKCS8vZG8gdGhyZWFkZWQgaW52b2tlCglzdCA9
IFNlcnZpY2UuZG9UaHJlYWRJbnZva2UoaW52b2tlZFN2Yy5jcmVhdGUodGFyZ2V0KSxjbG9uZWRQ
aXBlKTsKfQpjYXRjaCAoRXhjZXB0aW9uIGUpCi8vY2F0Y2ggYW55IGVycm9ycyBpbiBjbG9uaW5n
IG9yIGNyZWF0aW5nIHRoZSBuZXcgc2VydmljZSB0aHJlYWQKewoJU3lzdGVtLm91dC5wcmludGxu
KCJFcnJvciBleGVjdXRpbmcgbXlEb1RocmVhZEludm9rZToiK2UudG9TdHJpbmcoKSk7CgkvL2lu
c2VydCB5b3VyIG1lYW5pbmdmdWwgZXhjZXB0aW9uIGhhbmRsaW5nIGhlcmUKfQovL3B1dCB0aGUg
c2VydmljZSB0aHJlYWQgYmFjayBpbiB0aGUgcGlwZWxpbmUKSURhdGFVdGlsLnB1dChwaXBlbGlu
ZUN1cnNvciwic2VydmljZVRocmVhZCIsc3QpOwoKLy9hbHdheXMgZGVzdHJveSB5b3VyIGN1cnNv
ciB3aGVuIGRvbmUgdXNpbmcgaXQKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoKIA==</value>
</Values>
